# Define Base
FROM node:lts-alpine
RUN apk update && apk upgrade && \
    apk add --no-cache bash git
RUN apk add openssl
WORKDIR /usr/src/app
COPY package.json package-lock.json ./
COPY prisma ./prisma/
COPY .env ./
RUN yarn
RUN npx prisma generate
ENV NODE_ENV="development"
COPY . .
EXPOSE 4000
CMD [ "yarn", "start" ]
