FROM node:lts-alpine
WORKDIR /usr/src/app
RUN apk update && apk upgrade && \
	apk add --no-cache bash git && \
	apk add openssl
COPY package.json .
RUN yarn
COPY . .
ENV NODE_ENV="development"
EXPOSE 4000
ENTRYPOINT yarn start:dev
